// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY-T-nITFZnR2G2m7y1lAZHr4qymT62BA',
    appId: '1:312959488994:web:0e8c513578deec633c1fbb',
    messagingSenderId: '312959488994',
    projectId: 'chat-app-eeb08',
    authDomain: 'chat-app-eeb08.firebaseapp.com',
    storageBucket: 'chat-app-eeb08.appspot.com',
    measurementId: 'G-35FJ7EN7R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgwnU_C3BrqIhfOEY_mWMoNf6IiCSAmos',
    appId: '1:312959488994:android:e5115d43d0ef7f923c1fbb',
    messagingSenderId: '312959488994',
    projectId: 'chat-app-eeb08',
    storageBucket: 'chat-app-eeb08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtL6jQJZQeKDFZ2yKpLRSt2g07EC_xhvA',
    appId: '1:312959488994:ios:06008df5d955352f3c1fbb',
    messagingSenderId: '312959488994',
    projectId: 'chat-app-eeb08',
    storageBucket: 'chat-app-eeb08.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtL6jQJZQeKDFZ2yKpLRSt2g07EC_xhvA',
    appId: '1:312959488994:ios:06008df5d955352f3c1fbb',
    messagingSenderId: '312959488994',
    projectId: 'chat-app-eeb08',
    storageBucket: 'chat-app-eeb08.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY-T-nITFZnR2G2m7y1lAZHr4qymT62BA',
    appId: '1:312959488994:web:5de97f35f3ec978e3c1fbb',
    messagingSenderId: '312959488994',
    projectId: 'chat-app-eeb08',
    authDomain: 'chat-app-eeb08.firebaseapp.com',
    storageBucket: 'chat-app-eeb08.appspot.com',
    measurementId: 'G-72X9MGV4B7',
  );
}
